name: Regress

on: [workflow_dispatch, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: norio-nomura/action-swiftlint@3.2.1
        with: { args: --strict }
  pods:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with: { xcode-version: '12.5.1' }
      - name: Build
        run: |
          swift build -c release
          path=`swift build -c release --show-bin-path`
          echo "pods_path=$path/pods" >> $GITHUB_ENV
          swift run pods --version
      - uses: actions/upload-artifact@v2
        with:
          name: pods
          path: ${{ env.pods_path }}