name: Release

on:
  workflow_dispatch:
    inputs:
      bump-type:
        type: choice
        required: true
        options:
        - patch
        - minor
        - major

permissions:
  contents: write

jobs:
  bump:
    runs-on: macos-11.0
    steps:
      # Checkout with custom token for pushin to protected branch
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      # Update version in all files, commit, add tag and push
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "swiftyfinch@yandex.com"
          ruby .github/scripts/bump.rb ${{ github.event.inputs.bump-type }}

      # Build binary
      - uses: maxim-lobanov/setup-xcode@v1
        with: { xcode-version: '13.0' }
      - name: Build Pods
        run: |
          swift build -c release --arch arm64 --arch x86_64
          swift run pods --version
          path=`swift build -c release --arch arm64 --arch x86_64 --show-bin-path`
          mkdir -p pods/bin && mv $path/pods pods/bin
          zip -r pods.zip pods

      # Push tag and commit
      - run: |
          echo "release_tag=`git describe --tags --abbrev=0`" >> $GITHUB_ENV
          git push origin
          git push origin `git describe --tags --abbrev=0`

      # Create release and discussion
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: 🌱 Pods ${{ env.release_tag }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: pods.zip
          tag_name: ${{ env.release_tag }}